import type { Config } from './config';

/*
  A filing provider is whoever is legally allowed to submit the visa. A standard UAE tourist visa must be
  sponsored by a licensed tourism establishment, so in production this is a partner, not us:

  - manual:        your ops team submits each prepared application on the partner's portal, then records the
                   outcome in the ops console. Works with any licensed partner from day one.
  - partner_http:  the partner exposes an API. The adapter below is a template: map it to their documented fields.
  - sandbox:       a fake filer for development and demos. It approves everything after a short wait.
*/

export interface FilingPacket {
  applicationId: string;
  visa: { type: 'tourist'; days: 30 | 60; entry: 'single' };
  traveller: {
    given: string;
    surname: string;
    sex: 'M' | 'F' | '';
    dob: string;
    nationality: string;
    birthplace: string;
    passportNo: string;
    passportIssued: string;
    passportExpires: string;
    email: string;
    phone: string;
    profession: string;
  };
  trip: { arrival: string; departure: string; emirate: string };
  documents: { slot: string; mime: string; url: string }[];
  declarations: Record<string, boolean>;
  signature: { name: string; at: string };
}

export type FilingState = 'queued' | 'submitted' | 'processing' | 'needs_info' | 'approved' | 'rejected';

export interface FilingUpdate {
  state: FilingState;
  message?: string;
  permit?: { number: string; validUntil?: string; file?: { bytes: Uint8Array; mime: string }; url?: string };
}

export interface FilingProvider {
  name: Config['FILING_PROVIDER'];
  /** True when the provider pushes or pulls status on its own; false when ops record it by hand. */
  automatic: boolean;
  submit(p: FilingPacket): Promise<{ ref: string; update: FilingUpdate }>;
  poll?(ref: string, submittedAt: string): Promise<FilingUpdate>;
}

export function createProvider(c: Config): FilingProvider {
  if (c.FILING_PROVIDER === 'manual') return manualProvider();
  if (c.FILING_PROVIDER === 'partner_http') return partnerHttpProvider(c);
  return sandboxProvider(c);
}

/* ------------------------------------------------------------------ sandbox */

function sandboxProvider(c: Config): FilingProvider {
  return {
    name: 'sandbox',
    automatic: true,
    async submit(p) {
      return { ref: `SBX-${p.applicationId.slice(0, 8).toUpperCase()}`, update: { state: 'submitted', message: 'Sent to the sandbox filer' } };
    },
    async poll(ref, submittedAt) {
      const seconds = (Date.now() - Date.parse(submittedAt)) / 1000;
      if (seconds < Math.min(5, c.SANDBOX_APPROVE_AFTER_SECONDS / 2)) return { state: 'submitted' };
      if (seconds < c.SANDBOX_APPROVE_AFTER_SECONDS) return { state: 'processing', message: 'Under review' };
      const number = `SBX-${ref.slice(4)}-${String(Math.floor(seconds) % 997).padStart(3, '0')}`;
      return {
        state: 'approved',
        permit: { number, validUntil: new Date(Date.now() + 60 * 86400000).toISOString().slice(0, 10), file: { mime: 'application/pdf', bytes: samplePermitPdf(number) } },
      };
    },
  };
}

/** A small valid PDF so the whole download path can be tested end to end. Clearly marked as not a visa. */
export function samplePermitPdf(number: string) {
  const text = ['SANDBOX ENTRY PERMIT', `Number ${number}`, 'Generated by the Rihla sandbox filer.', 'NOT A VISA. NOT VALID FOR TRAVEL.'];
  const stream = `BT /F1 18 Tf 72 720 Td ${text.map((t, i) => `${i ? '0 -28 Td ' : ''}(${t.replace(/[()\\]/g, '')}) Tj`).join(' ')} ET`;
  const objs = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>',
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];
  let out = '%PDF-1.4\n';
  const offsets: number[] = [];
  objs.forEach((o, i) => {
    offsets.push(out.length);
    out += `${i + 1} 0 obj\n${o}\nendobj\n`;
  });
  const xref = out.length;
  out += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n${offsets.map((o) => `${String(o).padStart(10, '0')} 00000 n \n`).join('')}`;
  out += `trailer\n<< /Size ${objs.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return new TextEncoder().encode(out);
}

/* ------------------------------------------------------------------ manual (ops team) */

function manualProvider(): FilingProvider {
  return {
    name: 'manual',
    automatic: false,
    async submit(p) {
      return { ref: `OPS-${p.applicationId.slice(0, 8).toUpperCase()}`, update: { state: 'queued', message: 'Waiting for our team to file it with our licensed partner' } };
    },
  };
}

/* ------------------------------------------------------------------ partner API (template) */

/*
  TEMPLATE. Replace the request and response mapping with the partner's documented API before going live.
  Everything partner-specific is in `toPartner` and `fromPartner`; the rest of the app does not change.
*/
function partnerHttpProvider(c: Config): FilingProvider {
  const base = c.PARTNER_API_URL.replace(/\/$/, '');
  const headers = { authorization: `Bearer ${c.PARTNER_API_KEY}`, 'content-type': 'application/json' };
  const toPartner = (p: FilingPacket) => ({
    external_reference: p.applicationId,
    visa_type: p.visa.days === 60 ? 'TOURIST_60_SINGLE' : 'TOURIST_30_SINGLE',
    applicant: {
      first_name: p.traveller.given,
      last_name: p.traveller.surname,
      gender: p.traveller.sex,
      date_of_birth: p.traveller.dob,
      nationality: p.traveller.nationality,
      place_of_birth: p.traveller.birthplace,
      passport_number: p.traveller.passportNo,
      passport_issue_date: p.traveller.passportIssued,
      passport_expiry_date: p.traveller.passportExpires,
      email: p.traveller.email,
      mobile: p.traveller.phone,
      profession: p.traveller.profession,
    },
    travel: { arrival_date: p.trip.arrival, departure_date: p.trip.departure, emirate: p.trip.emirate },
    documents: p.documents.map((d) => ({ type: d.slot.toUpperCase(), url: d.url, content_type: d.mime })),
  });
  const fromPartner = (r: { status?: string; message?: string; visa_number?: string; visa_url?: string; valid_until?: string }): FilingUpdate => {
    const map: Record<string, FilingState> = { RECEIVED: 'submitted', IN_PROCESS: 'processing', ACTION_REQUIRED: 'needs_info', APPROVED: 'approved', REJECTED: 'rejected' };
    const state = map[(r.status ?? '').toUpperCase()] ?? 'processing';
    return { state, message: r.message, permit: state === 'approved' && r.visa_number ? { number: r.visa_number, url: r.visa_url, validUntil: r.valid_until } : undefined };
  };
  return {
    name: 'partner_http',
    automatic: true,
    async submit(p) {
      // The idempotency key lets the partner ignore a repeat if we retry after a timeout. The short timeout keeps
      // filing inside the payment webhook's window; a slow partner is simply retried by the scheduled run.
      const r = await fetch(`${base}/applications`, { method: 'POST', headers: { ...headers, 'idempotency-key': p.applicationId }, body: JSON.stringify(toPartner(p)), signal: AbortSignal.timeout(15_000) });
      if (!r.ok) throw new Error(`Partner rejected the submission: ${r.status} ${await r.text()}`);
      const body = (await r.json()) as { reference: string; status?: string; message?: string };
      return { ref: body.reference, update: fromPartner(body) };
    },
    async poll(ref) {
      const r = await fetch(`${base}/applications/${encodeURIComponent(ref)}`, { headers, signal: AbortSignal.timeout(20_000) });
      if (!r.ok) throw new Error(`Partner status failed: ${r.status}`);
      return fromPartner(await r.json());
    },
  };
}
